name: Dispatch workflows
on:
  push:
    branches: ['main', 'master']
  workflow_dispatch:
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch chowdhary.org build-site workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-site.yaml
          repo: chowdhary-org/chowdhary.org
          token: ${{ secrets.GH_PAT }}
      - name: Dispatch chowdhary.co build-site workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-site.yaml
          repo: chowdhary-org/chowdhary.co
          token: ${{ secrets.GH_PAT }}
